#ifndef _OFFSETS_H
#define _OFFSETS_H

#define OFFSET_TASK_READY 112
#define OFFSET_TASK_CR3 16
#define OFFSET_TASK_ESP0 20
#define OFFSET_TASK_CTX 28
#define OFFSET_TASK_CTX_EAX 28
#define OFFSET_TASK_CTX_EBX 32
#define OFFSET_TASK_CTX_ECX 36
#define OFFSET_TASK_CTX_EDX 40
#define OFFSET_TASK_CTX_ESI 44
#define OFFSET_TASK_CTX_EDI 48
#define OFFSET_TASK_CTX_EBP 52
#define OFFSET_TASK_CTX_ESP 56
#define OFFSET_TASK_CTX_EFLAGS 60
#define OFFSET_TASK_CTX_EIP 64
#define OFFSET_GDT_BASE_LOW 2
#define OFFSET_GDT_BASE_MID 4
#define OFFSET_GDT_BASE_HIGH 7
#define OFFSET_TSS_ESP0 4

#endif
